# Cloud Builder pipeline
# https://cloud.google.com/container-builder/docs/overview

steps:
# Perform maven build, omitting local docker operations
- name: 'maven:3.3.9-jdk-8'
  args: ['mvn', '-P-local-docker-build', '-P-test.local', '-Ddocker.tag.long=$_DOCKER_TAG', 'clean', 'install']
# Build the runtime container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=${_IMAGE}', '--no-cache', 'jetty9/target/docker']

# Test the built image

# Run our own integration tests
# TODO this requires the cloud sdk to be installed
# - name: 'maven:3.3.9-jdk-8'
#  args: ['mvn', '-P-local-docker-build', '-Ptest.remote', '-Djetty.test.image=${image}', 'verify']

# Runtimes-common structure tests
# See https://github.com/GoogleCloudPlatform/runtimes-common/tree/master/structure_tests
- name: 'gcr.io/gcp-runtimes/structure_test'
  args: ['--image', '${_IMAGE}', '-v', '--config', '/workspace/jetty9/target/test-classes/structure.yaml']

images: ['${_IMAGE}']
